name: Style

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  go_style:
    name: Go format & vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Check gofmt
        run: |
          fmtout=$(gofmt -s -l . | tee /dev/stderr)
          if [ -n "$fmtout" ]; then
            echo "The following files are not gofmt'd:" >&2
            echo "$fmtout" >&2
            exit 1
          fi
      - name: go vet
        run: go vet ./...
